
spring:
  # 数据源配置
  datasource:
    dynamic:
      primary: xunyee # 设置xunyee为默认数据源
      datasource:
        xunyee:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:postgresql://115.29.163.237:5432/vlkdj?currentSchema=xunyee&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        vlkdj:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:postgresql://115.29.163.237:5432/vlkdj?currentSchema=vlkdj&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        meta:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:postgresql://115.29.163.237:5432/vlkdj?currentSchema=meta&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        star:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://112.124.118.75:3306/star?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: wangxin
          password: wangxin@vlinkage
  #redis
  redis:
    host: localhost
    port: 6379
    database: 0

  data:
    mongodb:
      host: 115.29.163.237
      port: 27017
      database: xunyee
      username: vlkdj
      password: weiling@qinghai118


logging:
  level:
    org.springframework.data.mongodb: debug
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug

xunyee:
  config:
    # 系统部署到服务器 映射域名 用于微信支付回调
    host: http://luobin.iask.in