server:
  port: 80
spring:
  profiles:
    active: local
  # 返回参数时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    # 配置传参时间格式化
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
# mybatis-plus配置
mybatis-plus:
  configuration:
    # 关闭下划线转驼峰 不让获取数据为null
    map-underscore-to-camel-case: false


logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
#微信配置
wx:
  mp:
    configs:
      #移动应用
      - appid: wx40d52ce384db3975
        secret: 94189b599b464724996d684f93cbca52
      #公众号
      - appid: wxbe19aba223c2632a
        secret: 57688bf5611825cab2843907a0140198
  miniapp:
    configs:
        # 寻艺小程序
      - appid: wx6959ba05bf03effa
        secret: 02c55d754ecfe493f744c98d70c55028
        token: xunyee_miniprogram
        aesKey: DeRcJaD7SW4DKw6ADgu5ycxlHVoAY9lWI7maQx9v5zE
        msgDataFormat: JSON
  #支付
  pay:
    # 微信支付普通商户号 app支付 appId: wxf71bf12e04438f45
    mchId: 1562213661
    mchKey: Vlinkage20191108vvkk321Qinghailu


# 系统参数
sys-config:
  # 图片地址
  image-path: https://img.xunyee.cn/



knife4j:
  enable: true
  documents:
    - group: xunyee-api-2.0
      name: 寻艺文档md
      locations: classpath:markdwon/*
