
spring:
  # 数据源配置

  datasource:
    dynamic:
      primary: xunyee # 设置xunyee为默认数据源
      datasource:
        xunyee:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:postgresql://115.29.163.237:5432/vlkdj?currentSchema=xunyee&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        meta:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:postgresql://115.29.163.237:5432/vlkdj?currentSchema=meta&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
  #redis
  redis:
    host: 115.29.163.237
    port: 6378
    database: 0
    password: vlinkage80E2
  data:
    mongodb:
      database: xunyee
      username: vlkdj
      password: weiling@qinghai118
      host: 115.29.163.237
      port: 27017


