
spring:
  # 数据源配置
  datasource:
    dynamic:
      primary: xunyee # 设置xunyee为默认数据源
      datasource:
        xunyee:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://115.29.163.237:5432/vlkdj?currentSchema=xunyee&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        meta:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://115.29.163.237:5432/vlkdj?currentSchema=meta&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: vlkdj
          password: weiling@qinghai118
        star:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://112.124.118.75:3306/star?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: wangxin
          password: wangxin@vlinkage
  #redis
  redis:
    host: 115.29.163.237
    port: 6378
    database: 0
    password: vlinkage80E2
  data:
    mongodb:
      database: xunyee
      username: vlkdj
      password: weiling@qinghai118
      host: 115.29.163.237
      port: 27017

xunyee:
  config:
    host: http:/115.29.163.237:8089
